name: "Install tcld"
description: "Install Temporal Cloud management CLI"

runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22.x"
    - name: Checkout tcld repo
      uses: actions/checkout@v4
      with:
        repository: temporalio/tcld
        path: tcld
        ref: refs/tags/v0.20.0
    - name: Build tcld
      working-directory: tcld
      shell: bash
      run: make tcld
    - name: Move binary
      shell: bash
      run: |
        mv ./tcld/tcld /usr/local/bin